# Generated by Django 5.1.3 on 2024-12-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("place_id", models.CharField(primary_key=True, serialize=False)),
                ("name", models.CharField()),
                ("address", models.CharField()),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("rating", models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ("user_ratings_total", models.IntegerField()),
            ],
        ),
    ]
