name: frontend
description: "Better Bar Crawl App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  latlong2: ^0.9.0
  cupertino_icons: ^1.0.8
  open_route_service: ^1.2.6
  flutter_map: ^7.0.2
  geolocator: ^13.0.1
  app_settings: ^5.1.1
  provider: ^6.1.2
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env