name: frontend
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - frontend

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/frontend
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
            channel: main
      - name: Create env file
        run: |
          touch ../../.env
          echo "ORS_API_KEY=${{ secrets.ORS_API_KEY }}" > ../../.env
          pwd
          cat ../../.env
      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
